import urllib.request
r = urllib.request.urlopen('http://127.0.0.1:15800/admin/')
html = r.read().decode('utf-8', 'ignore')
print('html length:', len(html))
print('has opus-5:', 'opus-5' in html)
print('has gpt-5.6:', 'gpt-5.6' in html)
print('has glm-5.3:', 'glm-5.3' in html)
print('has deepseek:', 'deepseek' in html.lower())
print('has cheap:', 'cheap' in html.lower())
print('has brainstorming:', 'brainstorming' in html)
print('has playwright:', 'playwright' in html)
print('has models section id:', 'id="models"' in html)
print('has skills section id:', 'id="skills"' in html)
print('has m-count span:', 'm-count' in html)
print('has s-count span:', 's-count' in html)
